// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVUbs_7il6dkyWaBPiS3EIuqM-KMZQis',
    appId: '1:847331421929:android:c419466af1a4f9ce360a78',
    messagingSenderId: '847331421929',
    projectId: 'cartisan-production',
    storageBucket: 'cartisan-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhT6CBs5LSi0mMW3K1_4QphL9YYwwhjgw',
    appId: '1:847331421929:ios:2984005b88f71f2f360a78',
    messagingSenderId: '847331421929',
    projectId: 'cartisan-production',
    storageBucket: 'cartisan-production.appspot.com',
    androidClientId:
        '847331421929-9nu12sih4atfdvu6g5v5u3n3nm6e2ts4.apps.googleusercontent.com',
    iosClientId:
        '847331421929-u53tk5kkbm7bv99qjteff5qdqqghgqkm.apps.googleusercontent.com',
    iosBundleId: 'com.cartisan.app',
  );
}
